language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential autoconf nasm cmake ninja-build
script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
    - ninja && ninja test && cd ../test && ./test.sh
