language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential autoconf nasm
    - git clone https://github.com/mozilla/mozjpeg.git
    - cd mozjpeg
    - git fetch origin refs/tags/v3.2-pre:refs/tags/v3.2-pre
    - git fetch --all
    - git checkout tags/v3.2-pre
    - autoreconf -fiv
    - ./configure --with-jpeg8
    - make && sudo make install
    - cd ..
script:
    - make && make test && ./test.sh
